apiVersion: v1
kind: Namespace
metadata:
  name: team-a-dev
  labels:
    app.kubernetes.io/part-of: mirrord-rbac-demo
    # Kind enables PodSecurity admission. mirrord-agent needs NET_ADMIN /
    # SYS_PTRACE, so we relax the namespace to "privileged".
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b-dev
  labels:
    app.kubernetes.io/part-of: mirrord-rbac-demo
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
